fix: footer entity logo display
fccn/nau-themes pull request #41
Opened 2024-04-26 11:24 UTC by sandroscosta

fix logo display on footer funding section

2024-04-26 11:28 UTC, sandroscosta commented
Closes https://github.com/fccn/nau-technical/issues/97

2024-04-26 15:31 UTC, igobranco requested changes
It brakes on mobile:
![image](https://github.com/fccn/nau-themes/assets/67018/07c65fe9-229c-4d3a-9a33-011ba6fb012a)

2024-04-26 15:31 UTC, igobranco commented on edx-platform/nau-basic/lms/static/sass/partials/lms/theme/_footer.scss
>              img {
Add:

```scss
img {
    max-width: calc(100vw - 20px);
    max-height: 4.6rem;
}
```

2024-04-29 12:31 UTC, igobranco approved these changes
LGTM ✔️

2024-04-29 12:31 UTC, merged